include $(TOPDIR)/rules.mk

PROFILE_DESCRIPTION:=A more extensive list of suggested LibreMesh packages (-dnsmasq, -odhcpd-ipv6-only, -wpad-basic-mbedtls)
PROFILE_DEPENDS:= \
+profile-libremesh-suggested-packages \
+first-boot-wizard \
+wpad-mesh-openssl \
+lime-hwd-watchcat \
+lime-owut \
+pirania \
+shared-state-babel_links_info \
+shared-state-bat_links_info \
+shared-state-dnsmasq_servers \
+shared-state-network_nodes \
+shared-state-node_info \
+shared-state-wifi_links_info \
+ubus-tmate

include ../../profile.mk

# call BuildPackage - OpenWrt buildroot signature
