name: Build network profiles

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build packages
        uses: openwrt/gh-action-sdk@v7
        env:
          ARCH: "x86_64-openwrt-23.05"
          EXTRA_FEEDS: "src-git|libremesh|https://github.com/libremesh/lime-packages.git"
          FEEDNAME: "profiles"
          IGNORE_ERRORS: "n m y"
          KEY_BUILD: "${{ secrets.KEY_BUILD }}"

      - name: Upload packages to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: libremesh/lime-feed
          publish_dir: bin/packages/x86_64/profiles/
          destination_dir: profiles
